options:
  logging: CLOUD_LOGGING_ONLY
steps:
  #build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/inspired-memory-449608-f9/shop-copilot:latest', '.']
  #push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/inspired-memory-449608-f9/shop-copilot:latest']
  #deploy to cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'shop-copilot'
      - '--image'
      - 'gcr.io/inspired-memory-449608-f9/shop-copilot:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout'
      - '900s'
      - '--update-secrets=OPENAI_API_KEY=openai-api-key:latest,REPLICATE_API_TOKEN=replicate-api-key:latest'

images:
  - 'gcr.io/inspired-memory-449608-f9/shop-copilot:latest'