options:
  logging: CLOUD_LOGGING_ONLY
steps:
  #build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/inspired-memory-449608-f9/chatbot-app:latest', '.']
  #push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/inspired-memory-449608-f9/chatbot-app:latest']
  #deploy to cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','chatbot-app','--image','gcr.io/inspired-memory-449608-f9/chatbot-app:latest','--region','us-central1','--platform','managed','--set-env-vars', 'PORT=8080', '--allow-unauthenticated']

images:
  - 'gcr.io/inspired-memory-449608-f9/chatbot-app:latest'

# secret manager integration
# secrets:
#   - secret: 'openai-api-key'  # Name of the secret in Secret Manager
#     env-vars: '_OPENAI_API_KEY'
  
#   - secret: 'replicate-api-key'  # Name of the secret in Secret Manager
#     env-vars: 'REPLICATE_API_TOKEN'

#['run', 'deploy', 'chatbot-app', '--image', 'gcr.io/inspired-memory-449608-f9/chatbot-app:latest', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
# '--set-env-vars','OPENAI_API_KEY=${_OPENAI_API_KEY},REPLICATE_API_TOKEN=${_REPLICATE_API_TOKEN}',