apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-service
  template:
    metadata:
      labels:
        app: chatbot-service
    spec:
      containers:
        - name: chatbot-service
          image: gcr.io/inspired-memory-449608-f9/shop-copilot:latest
          ports:
            - containerPort: 80
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets  # This matches the Kubernetes secret name
                  key: openai-api-key   # This matches the key in the secret
            - name: REPLICATE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: replicate-api-key